name: image_gallery_saver_plus_max
description: Flutter升级3.35.7之后，对image_gallery_saver的插件升级（After Flutter upgraded to 3.35.7, the image_gallery_saver plugin was upgraded.）。
version: 1.0.5
homepage: https://github.com/HanQiGod/image_gallery_saver_plus_max

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.imagegallerysaverplusmax
        pluginClass: ImageGallerySaverPlugin
      ios:
        pluginClass: ImageGallerySaverPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
